sudo: required

services:
  - docker

before_install:
  - docker build -t yassinbelal/docker-react -f Dockerfile.dev .

script:
  - docker run yassinbelal/docker-react yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-563668005862"
  bucket_path: "docker-react"
  on:
    branch: master
